"""agregar_columnas_financieras

Revision ID: 7772da91e090
Revises: 20260227_0009
Create Date: 2026-02-27 17:17:02.699167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7772da91e090'
down_revision = '20260227_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('proveedores_codigo_key'), 'proveedores', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('proveedores_codigo_key'), 'proveedores', ['codigo'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
