"""crear_tablas_invima_y_limpiar_costos

Revision ID: be8e0122ba1f
Revises: 20260225_0006
Create Date: 2026-02-25 23:10:00.604611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8e0122ba1f'
down_revision = '20260225_0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos_cum',
    sa.Column('id_cum', sa.String(), nullable=False),
    sa.Column('expediente', sa.Integer(), nullable=True),
    sa.Column('consecutivocum', sa.Integer(), nullable=True),
    sa.Column('producto', sa.String(), nullable=True),
    sa.Column('titular', sa.String(), nullable=True),
    sa.Column('registrosanitario', sa.String(), nullable=True),
    sa.Column('fechavencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cantidadcum', sa.Float(), nullable=True),
    sa.Column('descripcioncomercial', sa.String(), nullable=True),
    sa.Column('estadocum', sa.String(), nullable=True),
    sa.Column('atc', sa.String(), nullable=True),
    sa.Column('descripcionatc', sa.String(), nullable=True),
    sa.Column('principioactivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cum')
    )
    op.create_index(op.f('ix_medicamentos_cum_estadocum'), 'medicamentos_cum', ['estadocum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicamentos_cum_estadocum'), table_name='medicamentos_cum')
    op.drop_table('medicamentos_cum')
    # ### end Alembic commands ###
