"""init_genhospi_catalog

Revision ID: def64bce7a59
Revises: be8e0122ba1f
Create Date: 2026-02-26 21:16:07.776479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def64bce7a59'
down_revision = 'be8e0122ba1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
